### ISSUE TITLE
Colors for FontAwesome Social Icons

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#48]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

There is no current styling for the social media icons in the footer.

Add the colors from below.

### Expected Behavior

```css
.fa-facebook {
    color: #1877f2;
}

.fa-github {
    color: #171515;
}

.fa-youtube {
    color: #ff0000;
}

.fa-discord {
    color: #5865f2;
}

.fa-reddit {
    color: #ff4500;
}

.ft-social-list li a :hover {
    color: #fff;
}
```

### Steps to Reproduce

Try it :+1: :-)
